Repository MicrosoftDocs/powerapps-docs.ja-jp, pull requests merged in 2019-07, with the labels that each got.

#24 Update faq-for-timeline-and-activity.md
  powerapps-docs/user/faq-for-timeline-and-activity.md
Labels: Accepted, Linguistic Suggestion

#25 Update use-flows.md
  powerapps-docs/user/use-flows.md
Labels: Accepted, Linguistic Suggestion

#26 Update intro-maker-portal.md
  powerapps-docs/maker/canvas-apps/intro-maker-portal.md
Labels: Accepted, Linguistic Suggestion

#27 Update limits-and-config.md
  powerapps-docs/maker/canvas-apps/limits-and-config.md
Labels: Accepted

#28 Update expense-report-install.md
  powerapps-docs/maker/canvas-apps/expense-report-install.md
Labels: Accepted, Linguistic Suggestion

#29 Update help-desk-install.md
  powerapps-docs/maker/canvas-apps/help-desk-install.md
Labels: Accepted, Linguistic Suggestion

#30 Update data-platform-create-app.md
  powerapps-docs/maker/canvas-apps/data-platform-create-app.md
Labels: Accepted, Linguistic Suggestion

#33 Update data-platform-cds-newentity-pq.md
  powerapps-docs/maker/common-data-service/data-platform-cds-newentity-pq.md
Labels: Accepted, Linguistic Suggestion

#32 Update create-custom-entity.md
  powerapps-docs/maker/common-data-service/create-custom-entity.md
Labels: Accepted, Linguistic Suggestion

#31 Update data-platform-create-entity.md
  powerapps-docs/maker/common-data-service/data-platform-create-entity.md
Labels: Accepted, Linguistic Suggestion

#34 Update create-edit-entities-portal.md
  powerapps-docs/maker/common-data-service/create-edit-entities-portal.md
Labels: Accepted, Linguistic Suggestion

#35 Update data-platform-import-export.md
  powerapps-docs/maker/common-data-service/data-platform-import-export.md
Labels: Accepted, Linguistic Suggestion

#36 Update customize-forms-sharepoint.md
  powerapps-docs/maker/canvas-apps/customize-forms-sharepoint.md
Labels: Accepted, Linguistic Suggestion

#37 Update customize-card.md
  powerapps-docs/maker/canvas-apps/customize-card.md
Labels: Accepted, Linguistic Suggestion

#38 Update data-platform-create-app-scratch.md
  powerapps-docs/maker/canvas-apps/data-platform-create-app-scratch.md
Labels: Accepted, Linguistic Suggestion

#41 Update connections-list.md
  powerapps-docs/maker/canvas-apps/connections-list.md
Labels: Accepted, Linguistic Suggestion

#40 Update get-started-test-drive.md
  powerapps-docs/maker/canvas-apps/get-started-test-drive.md
Labels: Accepted, Linguistic Suggestion

#46 Update cloud-storage-blob-connections.md
  powerapps-docs/maker/canvas-apps/connections/cloud-storage-blob-connections.md
Labels: Accepted, Linguistic Suggestion

#49 Update delegation-overview.md
  powerapps-docs/maker/canvas-apps/delegation-overview.md
Labels: Accepted, Linguistic Suggestion

#42 Update connection-common-data-service.md
  powerapps-docs/maker/canvas-apps/connections/connection-common-data-service.md
Labels: Accepted, Linguistic Suggestion

#47 Update add-data-connection.md
  powerapps-docs/maker/canvas-apps/add-data-connection.md
Labels: Linguistic Suggestion, Partially Accepted

#43 Update connection-sharepoint-online.md
  powerapps-docs/maker/canvas-apps/connections/connection-sharepoint-online.md
Labels: Accepted, Linguistic Suggestion

#50 Update working-with-data-sources.md
  powerapps-docs/maker/canvas-apps/working-with-data-sources.md
Labels: Accepted, Linguistic Suggestion

#51 Update working-with-tables.md
  powerapps-docs/maker/canvas-apps/working-with-tables.md
Labels: Accepted, Linguistic Suggestion

#54 Update add-screen-context-variables.md
  powerapps-docs/maker/canvas-apps/add-screen-context-variables.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#53 Update add-configure-controls.md
  powerapps-docs/maker/canvas-apps/add-configure-controls.md
Labels: Accepted, Linguistic Suggestion

#55 [LOC] "「こんにちは, world」" needs to be replaced with "Hello, world"
  powerapps-docs/maker/canvas-apps/add-configure-controls.md
Labels: Accepted, Linguistic Suggestion
